Numpy is a python package. It stands for 'Numerical python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

Operations using Numpy Using Numpy, a developer can perform the following operations:
Mathematical and logical operations on array
Fourrier transformation

In [6]:
import numpy as np
a = np.array([1,2,3]) # ----> delaring an array, 1-dimensional array
print(a)
print(a.ndim)

[1 2 3]
1


In [4]:
print(a.dtype)  # returns datatype of a

int32


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.size)  #returns no. of elements present in an array

3


In [7]:
b = np.array([[1,1,2],[3,4]]) #---> unequall distribution of elements failed in creation of array
print(b)

[list([1, 1, 2]) list([3, 4])]


In [8]:
print(b.dtype)

object


In [9]:
print(b.size) 

2


In [27]:
print(b.ndim) # Returns Dimension of the array

1


In [10]:
print(np.linspace(0,2,9)) #Creates a list from  0 to 2 ,containing nine elements

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### Intial Print Holders

In [2]:
import numpy as np
a = np.zeros(5) # default data type is float
print(a)  # --> returns an 1 dimensional array ,containing 0 as its integer element.

[0. 0. 0. 0. 0.]


In [61]:
a = np.zeros((2,3,4)) # default data type is float
# a = np.zeros((no of matrix,row,column))
print(a)  # --> returns two  3 x 4 dimensional array ,containing 0 as its integer element.

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [11]:
a1 =np.ones(5) # to create array of ones
print(a1)

[1. 1. 1. 1. 1.]


In [12]:
a2 =np.ones((3,2)) #create 3 x 2 dimensional array i.e 2 columns , 3 rows
print(a2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [66]:
a = np.ones((2,3,4)) # default data type is float
# a = np.ones((no of matrix,row,column))
print(a)  # --> returns two  3 x 4 dimensional array ,containing 1 as its integer element.

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [4]:
a3 = np.full((2,2),9) #create 3 x 3 dimensional array i.e 3 columns , 3 rows, containing 8 as its integer element
print(a3)

[[9 9]
 [9 9]]


In [69]:
a3 = np.full((2,3,3),8) #create 3 x 3 dimensional array i.e 3 columns , 3 rows, containing 8 as its integer element
print(a3)

[[[8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]]]


In [27]:
print(np.eye(4)) # Identity matrix of 0,1 ... creates a n-square matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
a = np.arange(0,24,1,dtype = int) # start,stop,step .. intial dtype = int
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [24]:
a = np.arange(0,24,5,dtype = float) # start,stop,step
print(a)

[ 0.  5. 10. 15. 20.]


In [26]:
a = np.arange(0.4,24.7,3,dtype = float) # start,stop,step
print(a)

[ 0.4  3.4  6.4  9.4 12.4 15.4 18.4 21.4 24.4]


In [29]:
b =a.reshape(2,4,3) #make 2 matrices of 3 by 4
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


#### Array aggregate functions

In [47]:
b = np.array([[1,2.3,3,4],[5,6,7,2],[9,2,2,12]])
print(b)
print(b.ndim)

[[ 1.   2.3  3.   4. ]
 [ 5.   6.   7.   2. ]
 [ 9.   2.   2.  12. ]]
2


In [48]:
print(b.max()) # ---> returns the maximum value present in the array 

12.0


In [49]:
print(b.max(axis = 0)) # ---> returns the maximum values in a column present in the array,and returns it as a row

[ 9.  6.  7. 12.]


In [50]:
print(b.min()) # ---> returns the minimum value present in the array

1.0


In [51]:
print(b.sum(axis = 0)) #columnwise sum

[15.  10.3 12.  18. ]


In [53]:
print(b.sum(axis = 1)) #rowwise sum

[10.3 20.  25. ]


In [56]:
print(b.mean())

4.608333333333333


In [54]:
print(b.mean(axis = 0))

[5.         3.43333333 4.         6.        ]


In [55]:
print(b.sum()) #summation of all elements

55.3


In [60]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [61]:
print(a.shape) #display no of rows and column
#resize the arrray
# this resizes the nd array

(2, 3)


In [62]:
b =a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


### Array maths

In [3]:
#array maths

a = np.array([1,2,3],float)
b = np.array([5,6,7],float)

print(a+b)
print(a-b)
print(a*b)



[ 6.  8. 10.]
[-4. -4. -4.]
[ 5. 12. 21.]


In [11]:
#array subsetting and slicing

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
print(a[0]) #first row

[1 2 3]


In [16]:
print(a[0:2,]) #first two rows all coloums

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
print(a[1:3,]) #2nd and 3rd row all coloumns

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(a[0:2,0]) #Row 1&2, column1

[1 5]


In [22]:
print(a[0,1:3]) #row 1 col 2 & 3

[2 3]


In [23]:
print(a[:2,1:3]) #first 2 rows & col 2 &3

[[2 3]
 [6 7]]


In [26]:
print(a[:,1:3]) #all rows & col 2 & 3

[[ 2  3]
 [ 6  7]
 [10 11]]


In [47]:
#Boolean Function in array

b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
print(b[b<3])

[1 2]


In [32]:
print(b[b>3])

[ 4  5  6  7  8  9 10 11 12]


In [33]:
#Array manipulation

b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.T) #Transpose of array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [34]:
print(np.ravel(b)) #Flatten the array

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [43]:
print(b.reshape(6,2)) #Reshape 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [35]:
c = np.array([10,20,30,40])
print(c)

[10 20 30 40]


In [37]:
print(np.append(b,c))

[ 1  2  3  4  5  6  7  8  9 10 11 12 10 20 30 40]


In [38]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(np.insert(b,1,22)) #Insert 22 at index postion 1, increase the array size


[ 1 22  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
print(np.delete(b,3)) #Delete element at index position 3

[ 1  2  3  5  6  7  8  9 10 11 12]


In [53]:
#Sorting array
x = np.array([2,1,4,3,5])
np.sort(x) #Ascending order sort

array([1, 2, 3, 4, 5])

In [50]:
np.sort(x)[::-1] #Descending order sort

array([5, 4, 3, 2, 1])

##### Numpy_Test

In [59]:
import numpy as np

#data01 = np.loadtxt("E:\\python\\numpy_test.txt", delimiter = ",",dtype = int)
data01 = np.loadtxt("E:\\python\\numpytest.txt", delimiter = ",",dtype = float)
np.set_printoptions(precision = 3)
print(data01)

[[100.     23.456]
 [200.     24.321]
 [300.     28.42 ]
 [400.     45.422]]


In [60]:
data01 = np.loadtxt("E:\\python\\numpytest.txt", delimiter = ",",dtype = int)
np.set_printoptions(precision = 3)
print(data01)

[[100  23]
 [200  24]
 [300  28]
 [400  45]]


In [2]:
#generation of random numbers NORMAL distribution

import numpy as np
x = np.random.normal(size = 5)
print(x)

[-0.20578802 -0.65970461 -0.47745682  0.29103749 -1.44597668]


In [9]:
#generation of random integers between 10 and 30
import numpy as np
x = np.random.randint(low = 20,high = 50,size = 6)
print(x)

[40 45 40 31 46 21]


In [11]:
#program toshuffle numbers 0 to 9.

import numpy as np
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
np.random.shuffle(x)
print(x)

[9 7 8 5 2 1 3 0 6 4]


In [20]:
print('Same result using permutation():\n')
print(np.random.permutation(10))

Same result using permutation():

[4 2 7 5 9 3 6 0 8 1]


##### use of min, max to normalise data

In [24]:
import numpy as np
x = np.random.random((3,3))
print('Orignal Array')
print(x)

Orignal Array
[[0.41678797 0.55157494 0.5724865 ]
 [0.82499015 0.54073785 0.68947262]
 [0.0713821  0.02685334 0.4698117 ]]


In [25]:
xmax, xmin = x.max(),x.min() #Min-Max Transformation
x = (x -xmin)/(xmax - xmin)
print('After Normalization: ')
print(x)

After Normalization: 
[[0.48855614 0.65743315 0.68363363]
 [1.         0.64385517 0.83020765]
 [0.05579089 0.         0.55499052]]


In [39]:
import numpy as np
x = np.random.randint(0,10,40)
print('Orignal Array')
print(x)

Orignal Array
[9 2 1 0 7 7 2 6 7 0 8 6 6 2 4 1 1 3 1 7 5 4 8 6 6 1 9 9 3 5 9 3 7 2 7 2 7
 9 0 7]


In [30]:
print(np.unique(x)) #Get a tuple of unique values and their frequency in numpy array
uniqueValues, occurCount = np.unique(x, return_counts = True)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
print("Unique Values : ", uniqueValues)
print("Occurence Count :", occurCount)
print("Most frequent value in the above array :")
print(np.bincount(x).argmax())

Unique Values :  [0 1 2 3 4 5 6 7 8 9]
Occurence Count : [2 2 4 4 3 3 5 8 3 6]
Most frequent value in the above array :
7


In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b) #commmon elements in a and b

array([2, 4])

In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b) #from a remove all of b

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(b,a) #from b remove all of a

array([6, 7, 8, 9])

In [24]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('Array Dimension :',a.ndim)

[[1 2 3]
 [4 5 6]]
Array Dimension : 2
