In [9]:
#Inverse  of a matrix
import math
import numpy as np

from numpy.linalg import inv
b = np.array([[1.,-1.,1.],[1.,1.,1.],[1.,2.,4.]]) #by default the datatype of a np-aaray is float64 
                                                  #and  without decimal it's int32
print(b,b.dtype)

binv  = inv(np.matrix(b))
binv = np.float16(binv) #transform the datatype from float64 to float16
print("\n ♥ INVERSE ♠ :\n",binv,binv.dtype)

Id = np.ceil(b.dot(binv)) #but to get identity matrix same approach isn't working for some reasons, so we use np.ceil 
print("\n ♦ Identity : \n",Id) 

[[ 1. -1.  1.]
 [ 1.  1.  1.]
 [ 1.  2.  4.]] float64

 ♥ INVERSE ♠ :
 [[ 0.3333  1.     -0.3333]
 [-0.5     0.5     0.    ]
 [ 0.1666 -0.5     0.3333]] float16

 ♦ Identity : 
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]
